# Generated by Django 2.1.1 on 2018-09-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='case number'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(blank=True, default='  vs  , et al.', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='casehandler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CaseHandler'),
        ),
        migrations.AlterField(
            model_name='case',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Club'),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract',
            field=models.BooleanField(choices=[('Yes', 'POEA SEC with CBA'), ('No', 'POEA SEC without CBA')], verbose_name='POEA SEC with CBA?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='correspondent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Correspondent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='counselofseafarer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CounselOfSeafarer', verbose_name="seafarer's counsel"),
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='legal_opinion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='localagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.LocalAgent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Principal'),
        ),
        migrations.AlterField(
            model_name='case',
            name='seafarer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Seafarer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='typeofclaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.TypeOfClaim'),
        ),
        migrations.AlterField(
            model_name='case',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Vessel'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.Correspondent'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
        migrations.AlterField(
            model_name='counselofseafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
        migrations.AlterField(
            model_name='seafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
    ]
