# Generated by Django 2.1.1 on 2018-10-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180929_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x000001E99916C208> <django.db.models.query_utils.DeferredAttribute object at 0x000001E99916C278>  vs  <django.db.models.query_utils.DeferredAttribute object at 0x000001E99916C518>, et al.', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='casehandler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CaseHandler'),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract',
            field=models.BooleanField(choices=[('YES', 'POEA SEC with CBA'), ('NO', 'POEA SEC without CBA')], verbose_name='POEA SEC with CBA?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='counselofseafarer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CounselOfSeafarer', verbose_name="seafarer's counsel"),
        ),
    ]
