# Generated by Django 2.1.1 on 2018-10-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20181001_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casehandler',
            options={'verbose_name_plural': 'Case Handlers'},
        ),
        migrations.AlterModelOptions(
            name='counselofseafarer',
            options={'verbose_name_plural': 'Counsels of Seafarers'},
        ),
        migrations.AlterModelOptions(
            name='localagent',
            options={'verbose_name_plural': 'Local Agents'},
        ),
        migrations.AlterModelOptions(
            name='suffix',
            options={'verbose_name_plural': 'suffixes'},
        ),
        migrations.AlterModelOptions(
            name='typeofclaim',
            options={'verbose_name_plural': 'Types of Claim'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x000001CEF458B1D0> <django.db.models.query_utils.DeferredAttribute object at 0x000001CEF458B240>  vs  <django.db.models.query_utils.DeferredAttribute object at 0x000001CEF458B748>, et al.', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='correspondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Correspondent'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
        migrations.AlterField(
            model_name='counselofseafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
        migrations.AlterField(
            model_name='seafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.Suffix'),
        ),
    ]
