# Generated by Django 2.1.1 on 2018-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20181002_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casehandler',
            options={'verbose_name': 'Case Handler', 'verbose_name_plural': 'Case Handlers'},
        ),
        migrations.AlterModelOptions(
            name='counselofseafarer',
            options={'verbose_name': 'Counsel of Seafarer', 'verbose_name_plural': 'Counsels of Seafarers'},
        ),
        migrations.AlterModelOptions(
            name='localagent',
            options={'verbose_name': 'Local Agent', 'verbose_name_plural': 'Local Agents'},
        ),
        migrations.AlterModelOptions(
            name='typeofclaim',
            options={'verbose_name': 'Type of Claim', 'verbose_name_plural': 'Types of Claim'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x0000014A70C3A240> <django.db.models.query_utils.DeferredAttribute object at 0x0000014A70C3A2B0>  vs  <django.db.models.query_utils.DeferredAttribute object at 0x0000014A70C3A7B8>, et al.', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract',
            field=models.CharField(choices=[('YES', 'POEA SEC with CBA'), ('NO', 'POEA SEC without CBA')], max_length=20, verbose_name='POEA SEC with CBA?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='ref_no',
            field=models.CharField(max_length=30, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_day1',
            field=models.DateField(blank=True, null=True, verbose_name='1st day of treatment'),
        ),
    ]
