# Generated by Django 2.1.1 on 2018-10-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20181002_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Case Title'),
        ),
        migrations.AlterField(
            model_name='case',
            name='casehandler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CaseHandler', verbose_name='Case Handler'),
        ),
        migrations.AlterField(
            model_name='case',
            name='counselofseafarer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cases.CounselOfSeafarer', verbose_name="Seafarer's Counsel"),
        ),
        migrations.AlterField(
            model_name='case',
            name='legal_opinion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Legal Opinion Rendered?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='localagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.LocalAgent', verbose_name='Local Agent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='treatment_day1',
            field=models.DateField(blank=True, null=True, verbose_name='1st Day of Treatment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='typeofclaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.TypeOfClaim', verbose_name='Type of Claim'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='casehandler',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=4, verbose_name='Middle Initial'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Club Name'),
        ),
        migrations.AlterField(
            model_name='correspondent',
            name='correspondent_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Correspondent Name'),
        ),
        migrations.AlterField(
            model_name='counselofseafarer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='counselofseafarer',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='counselofseafarer',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=4, verbose_name='Middle Initial'),
        ),
        migrations.AlterField(
            model_name='localagent',
            name='localagent_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Local Agent Name'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='principal_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="Principal's Name"),
        ),
        migrations.AlterField(
            model_name='seafarer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='seafarer',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='seafarer',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=4, verbose_name='Middle Initial'),
        ),
        migrations.AlterField(
            model_name='typeofclaim',
            name='claim_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Type of Claim'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_name',
            field=models.CharField(max_length=75, primary_key=True, serialize=False, verbose_name='Vessel Name'),
        ),
    ]
