# Generated by Django 2.1.1 on 2018-09-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_no', models.CharField(max_length=30, verbose_name='reference number')),
                ('case_no', models.CharField(max_length=50, verbose_name='case number')),
                ('case_title', models.CharField(default='  vs  , et al.', max_length=200)),
                ('contract', models.BooleanField(verbose_name='POEA SEC with CBA')),
                ('diagnosis', models.TextField()),
                ('treatment_day1', models.DateTimeField(blank=True, null=True, verbose_name='1st day of treatment')),
                ('legal_opinion', models.BooleanField()),
                ('remarks', models.TextField(blank=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHandler',
            fields=[
                ('casehandler_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=4)),
                ('last_name', models.CharField(max_length=35)),
                ('nickname', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('correspondent_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CounselOfSeafarer',
            fields=[
                ('counselor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=4)),
                ('last_name', models.CharField(max_length=35)),
                ('nickname', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAgent',
            fields=[
                ('localagent_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('principal_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seafarer',
            fields=[
                ('seafarer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=4)),
                ('last_name', models.CharField(max_length=35)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('suffix', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfClaim',
            fields=[
                ('claim_type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='type of claim')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vessel_name', models.CharField(max_length=75, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='seafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Suffix'),
        ),
        migrations.AddField(
            model_name='counselofseafarer',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Suffix'),
        ),
        migrations.AddField(
            model_name='casehandler',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Correspondent'),
        ),
        migrations.AddField(
            model_name='casehandler',
            name='suffix',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Suffix'),
        ),
        migrations.AddField(
            model_name='case',
            name='casehandler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.CaseHandler'),
        ),
        migrations.AddField(
            model_name='case',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Club'),
        ),
        migrations.AddField(
            model_name='case',
            name='correspondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Correspondent'),
        ),
        migrations.AddField(
            model_name='case',
            name='counselofseafarer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.CounselOfSeafarer', verbose_name="seafarer's counsel"),
        ),
        migrations.AddField(
            model_name='case',
            name='localagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.LocalAgent'),
        ),
        migrations.AddField(
            model_name='case',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Principal'),
        ),
        migrations.AddField(
            model_name='case',
            name='seafarer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Seafarer'),
        ),
        migrations.AddField(
            model_name='case',
            name='typeofclaim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.TypeOfClaim'),
        ),
        migrations.AddField(
            model_name='case',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Vessel'),
        ),
    ]
